language: generic
notifications:
  email: false
  slack:
    rooms:
      secure: c/9g2dMUDjPMaShUiVsEwTINSH2xAnSOZ/oLhyRl79dFMr4Utr6xMscyNdwtxGcf1ZLuAh2FJ5rECP39Ih/ZYD1LQsthJmZSG19ACSYR8hGQZHTbCT8++TqnITwL1mQ4UMqkEcQh8wx2SgumCCQb2Xbz8WPFrgpvQCLSTgr/Cdgrmx4978w1z3dkulrgND7KZJAh79TUlST59EhSdU16AJ+V7rG5LIUvikkP0rTpx/Hjgr7gRfI/mrGkov1t9n+w0mV204FfYLhciO4FjZGTXScspoo8ubfYHhcf3+s+MOdJK8WB1t20G+iRsMGhqOgGMsW9qgHo2q9wxJhiKOgdzUx78/H/SGqTOr5vp48XkrvbHANJqlt3WUJfyx9h/FznM0RIMVUIcYVwUQYz5AuAOZJtOcBNNFR6WOWfbIpFWTNBwLzTv0rjJd3sYc0EX/+ChR++J+yIe9bldi9IAzwhUGlzy1d47EZWE29rYWsuD+QrmGiUaovAJ2OI+dGK2pmrxR8O7yQz8YyRDhZsmxtWKZB2VkvCHyYiZjyNfBP6a0Q1zVO1dM5CwTTjWfBdSpi7eiHko0KK8ocR5OPnVRYu8owBWSUHma6ISPcOD+RnSGhyW23Qp4ija0dzfDkMeNxal7tbgn4gjqFAyHuoLLsP0Lz8FgmrT2JmT4loaXbZRyA=
branches:
  only:
  - master
script:
- ls -lah
after_success:
- "./travis-remote-trigger.sh"
