language: generic
notifications:
  email: false
  slack:
    rooms:
      secure: csbiqkGi0dERVEuxJzdrpTgG9CbEg7aNHKMe6owoIX8XLOtXu61txs6cjSyMhDnTncaeQaA3p8qyoG9nixSpNsvYGK0tO1k7UfFOi/0+q109tfE14Ketn9bJGtdmlOibEikZNd0Y+3d0z+kHfqqgv+uQUhSgwLtMfREzKeFM82e92j//c8SJ/LVoa8fpiLg3qwlKwrSsr14MJxOjmDkUpE1XDPLVnMQc5DmAb8m2u6WyAC/Lg++9RFSyvx+A5ccXSPDjKEn5gea1ji3Pefb1LxRaIjNuudyD9EEFrtQ4SIXO3i1hskcE+Ai5PixW0CaSt2tmr38W/36OZWytsWCry6x1djtPl797dGnEgOieZiZW4MkaJdbbSG5AjrrSBK+sZWo3LH7QznA0jd+oIYuFtGc9i7n12FrrI6FWakGpYaedpkdSUDng9pqR3ljeKaqpa5JbpyJ1+XBlKREYyfKKT/O6MLVVZxJ8pu+nNu7OKzBC7kkfcXFr/QZUY9eyUDok8v9Q7uYtR4sRwPyp2iCMAXmRw1HE8mOUgSH8P/WHTd/0+wq3aehRL4z1IqhSAlqyAyNI8PPRFXxg1xalVxtJY1ib0wZsO9TVpwu9AvlG7UtjGSZ2BdQ6+j42NbpeLfQKdJQN8rSBf0AZgorUh9g7Q/Lz+kUMyQARzG3O/17TD8s=
branches:
  only:
  - master
script:
- ls -lah
after_success:
- "./travis-remote-trigger.sh"
