language: generic
notifications:
  email: false
  slack:
    secure: HeSYt8dSyI8x6Pgh8d4Gnia2DV1iT/ee42onWnrCTvnhzX48VNNwJsy+9nP/d9FiwxuH4ANHj+fu4kzBYe87TZiw3yOifw9Un53kWIySIaEXHEovuQ2EMYJtjuNUXUxP9BckB/YgzJ4Tbjk3YzkdFnQcxEzgqbRRKHn8q9SazMROQTVwtgAkV5ItAJkELqUfph5+iiyhboPvTH2+opwmXwgca6V+4L5rHuPunrrn60SAlgLiLVvOcmk0xqyZpM6h1hIzBZOBg7lWvE2gPdvYJtIo7yNub2f1z1qgBHskKaoDmotTcF49lsRyrCpMcrlmJF1PWDgkzNkjQiEY6XGoYjBRsD6lls2oCio2R+6A+nSQsxKiUtslGc6AsKj8pPIUs2hvTFIkeV5zdsG99YfNHxn3XVp88wj56NzJKzu2Neose9FpnxYVb+uZTNr4TMF7UZMLKwVU3Ao8Fj/VV0iNaqZaVD95rjr/zyajPxghaZ4Wt5BMgdbuIsQCiWlVmRB+8nKQEy7ArEr5MywoAWoD6Wg4ZNwZoMsXWKmtqg39BB7fEPxW7yZIEBJnD+rZ3AzhPNZv11n4YeLP3gP+mFEzPV3bTiPySJf7m9cTCwdkTfZnfcRhgbAYmSoav97WLS9nIa7C3apdXMiCX0ypIfvK5C37n1wth25zqH7j58emxRY=
branches:
  only:
  - master
script:
- ls -lah
after_success:
- "./travis-remote-trigger.sh"
