language: generic
notifications:
  email: false
  slack:
    rooms:
      secure: K6MiolAIVaKBbIVe97srt5xBKdE/5THYhAy7wmkNNY+A5NNxny8klqEh9unAje/avIYju5G4jgQmEk0drvBB61oeuD5bq6WfzF64zOV5X/hx3v5HsysLit31Bb/My0+r4ffdbR4vXqgDtEv/ZOZExKT9CnIo5h4U4fGMvaxr6DIVDqyL+zvgy6ROjU/cwRzVPAvj0UvGRUYTJANaTYZKdWqAsq0dJP6sL8BxVLAQaV+W5i3vTVpRacj7vWRnohXbGs7Rt1sWdj0eyv4WWzDRcbZfMedaKq1OGvXGOxpZIOKGYcC/a57WMFrKaC02N0GQiIa5yr62wozDc31t3OHQ7LSz5I0nU0R3sK0SyGCQlGHBWI0xJtp16TjyIeJHD4jBvpOoyG05KQQOT4Mn/E0ApL+tPPAwuiCVujN0MjyBnMv1aFIE+gHFzzK99Fgc0D1FXC/ybdR9Ee8M33YDai610VhsYcoP4OFohimMSwYVok2QasMphf1xIeDVpID+FC1leNDDsbzoLEdSzG0lBKLemgbWdx6j5cdY1eo7RAtg0U08qdyTnhV0lnbaNNVV5d+Pjr28FXfUwZ+X+hsazkJFRsSQMrkNnlJAnAC+JtRN/TBMrAiwB1ci0WTwm8Hk0bp4my+KLLsqJRckAGlgl9qbs925EEain/KkbfuZULothEA=
branches:
  only:
  - master
script:
- ls -lah
after_success:
- "./travis-remote-trigger.sh"
