---
#- hosts: tag_name_pcgr
- hosts: all
  user: ubuntu
  gather_facts: no
  tasks:
    - name: Fetch VCF from S3 bucket
      s3:
        bucket: "{{ pcgr.s3_vcf_bucket }}" 
        object: "{{ pcgr.input_vcf }}"
        dest: "{{ pcgr.mount }}"
        mode: get

    - name: Copy PCGR configuration and thresholds
      copy:
         src: files/pcgr_configuration.toml
         dest: "{{ pcgr.mount }}"
         mode: 0644

    - name: Run PCGR with VCF payload and default configuration
      shell: ./pcgr.py --input_vcf "{{ pcgr.input_vcf }}" . output pcgr_configuration.toml "{{ pcgr.input_vcf }}"
