---
- hosts: tag_name_pcgr
  connection: local
  gather_facts: no
  tasks:
    - name: Teardown EC2 instance
      ec2:
         state: "absent"
         region: "{{ aws.region }}"
         wait: yes
