---
name: on_pcgr_s3_upload
pack: pcgr
description: Rule to act on pcgr.up trigger instances
enabled: false

trigger:
  type: pcgr.up

criteria:
      {}

action:
  ref: chatops.post_message
  parameters:
    message: 'VCF file detected on s3://pcgr bucket'
    channel: '#arteria-dev'
#    channel: '#biobots'
