---
name: on_pcgr_s3_upload
pack: pcgr
description: Rule to act on pcgr.up trigger instances
enabled: false

trigger:
  type: pcgr.up

criteria:
      {}

action:
  ref: pcgr.up
  parameters:
    vcf_filename: "{{trigger.fname}}"
